site_name: FAQS IngInf
theme:
  name: material
  palette:
    primary: green
    accent: green
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  features:
    - navigation.instant
nav:
    - Home: 'index.md'
    - Orari: 'orari.md'
    - Laurea: 'laurea.md'
    - Esami: 'esami.md'
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-S0SF7FF38F
