site_name: FAQS for i3s
theme:
  name: material
  palette:
    primary: green
    accent: lime
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  features:
    - navigation.instant
nav:
    - Home: 'index.md'
    - Laurea: 'laurea.md'
    - Esami: 'esami.md"
